#pragma checksum "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\Layout\MainLayout.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5a7fb4b95e40caa2fad602b39b7b632c4d2a0054f350cd6ced6562841088de86"
// <auto-generated/>
#pragma warning disable 1591
namespace OnlineBookShop.Components.Layout
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,45) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.ComponentModel.DataAnnotations

#line default
#line hidden
#nullable disable
    ;
    #nullable restore
    public partial class MainLayout : 
#nullable restore
#line (1,11)-(1,30) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\Layout\MainLayout.razor"
LayoutComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "class", "page");
            __builder.AddMarkupContent(2, "<div class=\"sidebar\"></div>\r\n\r\n    ");
            __builder.OpenElement(3, "main");
            __builder.AddMarkupContent(4, "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n        <link rel=\"stylesheet\" href=\"lib/bootstrap/dist/css/MainLayout.razor.css\">\r\n\r\n        ");
            __builder.OpenElement(5, "div");
            __builder.AddAttribute(6, "class", "d-flex flex-column min-vh-100");
            __builder.OpenComponent<global::OnlineBookShop.Components.Layout.NavMenu>(7);
            __builder.CloseComponent();
            __builder.AddMarkupContent(8, "\r\n\r\n            ");
            __builder.OpenElement(9, "div");
            __builder.AddAttribute(10, "class", "main-content");
            __builder.AddContent(11, 
#nullable restore
#line (16,18)-(16,22) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\Layout\MainLayout.razor"
Body

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(12, "\r\n\r\n\r\n            ");
            __builder.AddMarkupContent(13, "<footer class=\"bg-dark text-light text-center p-3 mt-auto\">\r\n                &copy; 2025 Книжковий магазин\r\n            </footer>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
