#pragma checksum "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\Layout\NavMenu.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "75601916a9c1ec0cd9128ce37fc2a4452800f45114f95ee0108b84c8644e45e6"
// <auto-generated/>
#pragma warning disable 1591
namespace OnlineBookShop.Components.Layout
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,45) "C:\Users\Asus\RiderProjects\OnlineShopWebApp\OnlineBookShop\Components\_Imports.razor"
using System.ComponentModel.DataAnnotations

#line default
#line hidden
#nullable disable
    ;
    #nullable restore
    public partial class NavMenu : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "nav");
            __builder.AddAttribute(1, "class", "navbar navbar-expand-lg navbar-dark bg-dark px-4");
            __builder.AddMarkupContent(2, "<a class=\"navbar-brand fw-bold text-uppercase text-light\" href=\"/\">BookStore</a>\r\n\r\n    ");
            __builder.AddMarkupContent(3, "<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Перемкнути навігацію\"><span class=\"navbar-toggler-icon\"></span></button>\r\n\r\n    ");
            __builder.OpenElement(4, "div");
            __builder.AddAttribute(5, "class", "collapse navbar-collapse");
            __builder.AddAttribute(6, "id", "navbarNav");
            __builder.OpenElement(7, "ul");
            __builder.AddAttribute(8, "class", "navbar-nav me-auto mb-2 mb-lg-0");
            __builder.OpenElement(9, "li");
            __builder.AddAttribute(10, "class", "nav-item");
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Routing.NavLink>(11);
            __builder.AddComponentParameter(12, "class", "btn btn-outline-light catalog-btn");
            __builder.AddComponentParameter(13, "href", "catalog");
            __builder.AddAttribute(14, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(15, "<i class=\"bi bi-book me-1\"></i> Каталог книг\r\n                ");
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(16, "\r\n\r\n        \r\n        ");
            __builder.AddMarkupContent(17, @"<form class=""d-flex me-auto ms-3""><input class=""form-control search-box"" type=""search"" placeholder=""Пошук книг..."" aria-label=""Search"">
            <button class=""btn btn-outline-light ms-2"" type=""submit""><i class=""bi bi-search""></i></button></form>

        
        ");
            __builder.OpenElement(18, "div");
            __builder.AddAttribute(19, "class", "auth-links ms-auto");
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Routing.NavLink>(20);
            __builder.AddComponentParameter(21, "href", "/login");
            __builder.AddComponentParameter(22, "class", "nav-link d-inline text-light");
            __builder.AddAttribute(23, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(24, "Вхід");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(25, "\r\n            ");
            __builder.AddMarkupContent(26, "<span class=\"text-light\"> / </span>\r\n            ");
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Routing.NavLink>(27);
            __builder.AddComponentParameter(28, "href", "/register");
            __builder.AddComponentParameter(29, "class", "nav-link d-inline text-light");
            __builder.AddAttribute(30, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(31, "Реєстрація");
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
